import json
from upath import UPath as Path
from snakebids import set_bids_spec
import pandas as pd
from collections import defaultdict
import os


configfile: "config/config.yml"


container: config["containers"]["spimprep"]


# use expandvars so we can use e.g. '$SLURM_TMPDIR'
root = os.path.expandvars(config["root"])
work = os.path.expandvars(config["work"])
resampled = Path(root) / "derivatives" / "resampled"


# this is needed to use the latest bids spec with the pre-release snakebids
set_bids_spec("v0_11_0")

# read datasets tsv
dtype = defaultdict(lambda: str, num_tiles=int)
datasets = pd.read_csv(config["datasets"], sep="\t", dtype=dtype)


include: "rules/common.smk"


rule all:
    input:
        get_all_targets(),
        get_bids_toplevel_targets(),
        get_qc_targets(),
        get_save_work_targets(),
    localrule: True


include: "rules/import.smk"
include: "rules/flatfield_corr.smk"
include: "rules/bigstitcher.smk"
include: "rules/ome_zarr.smk"
include: "rules/bids.smk"
include: "rules/qc.smk"
