import json
from pathlib import Path
from snakebids import bids, set_bids_spec
import pandas as pd
import os


configfile: "config/config.yml"


container: config["containers"]["spimprep"]


# use expandvars so we can use e.g. '$SLURM_TMPDIR'
root = os.path.expandvars(config["root"])
work = os.path.expandvars(config["work"])

# this is needed to use the latest bids spec with the pre-release snakebids
set_bids_spec("v0_10_1")

# read datasets tsv
datasets = pd.read_csv(
    config["datasets"],
    sep="\t",
    dtype={
        "subject": str,
        "sample": str,
        "acq": str,
        "stain_0": str,
        "stain_1": str,
        "num_tiles": int,
    },
)


include: "rules/common.smk"


rule all:
    input:
        get_all_targets(),


include: "rules/import.smk"
include: "rules/flatfield_corr.smk"
include: "rules/bigstitcher.smk"
include: "rules/ome_zarr.smk"
include: "rules/atlasreg.smk"
