rule generate_flatfield_qc:
    input:
        uncorr=bids(
                    root=work,
                    subject="{subject}",
                    datatype="micr",
                    sample="{sample}",
                    acq="{acq}",
                    desc="raw",
                    suffix="SPIM.zarr",
                ),
        corr=bids(
                    root=work,
                    subject="{subject}",
                    datatype="micr",
                    sample="{sample}",
                    acq="{acq}",
                    desc="flatcorr",
                    suffix="SPIM.zarr",
                ),
    params:
        ff_s_start=config["report"]["flatfield_corrected"]["slice_start"],
        ff_s_step=config["report"]["flatfield_corrected"]["slice_step"],
        ff_cmap=config["report"]["flatfield_corrected"]["colour_map"],
    output:
        html='qc/sub-{subject}_sample-{sample}_acq-{acq}_flatfieldqc.html',
        images_dir=directory('qc/images/sub-{subject}_sample-{sample}_acq-{acq}')
    log:
        bids(
            root="logs",
            datatype="generate_flatfield_qc",
            subject="{subject}",
            sample="{sample}",
            acq="{acq}",
            suffix="log.txt",
        ),
    script:
        "../scripts/generate_flatfield_qc.py"


