name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: "pip install --no-deps -r .github/workflows/snakemake_action_requirements.txt"
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v2

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        stagein: "pip install --no-deps -r .github/workflows/snakemake_action_requirements.txt"
        snakefile: workflow/Snakefile
        args: "--sdm apptainer --show-failed-logs --cores 1 --all-temp"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        stagein: "pip install --no-deps -r .github/workflows/snakemake_action_requirements.txt"
        snakefile: workflow/Snakefile
        args: "--report report.zip"
